import React, {Component} from 'react'
import ReactDOM from 'react-dom'

const Terms = (props) => (
  <div className="reveal signup-athlete" id="user-agreement" data-reveal data-animation-in="fade-in slow" data-animation-out="fade-out fast">
    <h1 className="section-heading">User Agreement</h1>
    <button className="close-button" data-close="" aria-label="Close modal" type="button">
      <span aria-hidden="true" className="psr-icons icon-x"></span>
    </button>
    <div>
      <h5>User Agreement, terms and conditions, and cancellation policy</h5>
      <p>PLEASE READ THE FOLLOWING TERMS AND CONDITIONS OF USE FOR THIS WEBSITE CAREFULLY.</p>
      <p>By using this website you are agreeing to the Terms and Conditions outlined herein. You should check the content of these Terms and Conditions periodically for changes as PersonalSportRecord.com (PersonalSportRecord.com) reserves the right to make such changes, without notice to you. By using this website after such changes have been made and posted you agree to accept those changes, whether you have reviewed them or not. If at any time, you do not agree to these Terms and Conditions or changes to these Terms and Conditions, your sole remedy is to discontinue use of this website. Any use or continuation of use of this Website is deemed to be your acceptance of these Terms and Conditions or any changes to these Terms and Conditions.</p>
      <p>PersonalSportRecord.com maintains this Internet website as a service to the global Internet community. All content, both images and text is the property of PersonalSportRecord.com and is not to be copied and or modified without the written consent of PersonalSportRecord.com. PersonalSportRecord.com reserves all rights to the content. Only where expressly authorized by PersonalSportRecord.com may members download content for their own personal, non-commercial use in accordance with these Terms and Conditions or the written consent of PersonalSportRecord.com.</p>
      <p>PersonalSportRecord.com will use reasonable efforts to include accurate and up-to-date information, but makes no warranties or representations as to the accuracy or completeness of this information. PersonalSportRecord.com shall not be liable for damages of any kind arising from your use, access, or inability to access this or any PersonalSportRecord.com maintained website or your reliance on the information contained within this or any PersonalSportRecord.com maintained website.</p>
      <p>PersonalSportRecord.com takes no responsibility for links within this or any PersonalSportRecord.com maintained website. PersonalSportRecord.com shall not be liable for any damages or consequences that arise from your transfer to any other websites via a link within this or any PersonalSportRecord.com maintained website. PersonalSportRecord.com makes no warranties or representations of any kind in relation to websites owned, operated, represented, maintained, used or occupied by persons, parties or entities other than PersonalSportRecord.com.</p>
      <p>PersonalSportRecord.com will collect personal information that may identify you, the user, only when it is offered voluntarily by you. PersonalSportRecord.com uses this information in accordance with its Privacy Policy. Please review the Privacy Policy and consider it part of these Terms and Conditions.</p>
      <p>You are solely responsible for maintaining the secrecy of your passwords and account information. Please be diligent in protecting the secrecy of such information as you will be responsible and liable for any and all use of your password or account, notwithstanding that such use was not authorized by you.</p>
      <p>Athletic Training Materials and Content</p>
      <p>Not all exercises or diets are suitable for everyone. Before you begin any programs or suggestions included on the PersonalSportRecord.com web properties, you should have the permission of your doctor to change your diet and participate in vigorous exercise. If you ever feel discomfort or pain while exercising, discontinue the exercise and seek medical advice. The instructions and advice presented by PersonalSportRecord.com are in no way intended as a substitute for professional medical advice.</p>
      <p>The creators, producers, participants and distributors of PersonalSportRecord.com products and services reserve the right to refuse membership at their sole discretion and disclaim any liability or loss in connection with the exercise and advice provided herein.</p>
      <ol>
      <li><strong>INFORMATION:</strong> All information presented by PersonalSportRecord.com is for entertainment and informational purposes only. The material is not intended to be a substitute for medical and sport performance counselling. Before adhering to any of the information or recommendations presented by PersonalSportRecord.com please consult with your own physician or healthcare practitioner. PersonalSportRecord.com reserves the right to refuse or cancel membership for any reason, including certain medical conditions.</li>
      <li><strong>GENERAL TERMS AND CONDITIONS:</strong> You agree to: (a) maintain the security of your user identification, password and other confidential information relating to your PersonalSportRecord.com account(s); (b) be responsible for all charges resulting from the use of your PersonalSportRecord.com account, including unauthorized use; (c) take such steps to discontinue the occurrence of any unauthorized use by notifying PersonalSportRecord.com immediately and changing your password; and (d) keeping your e-mail address and other personal information current.</li>
      <li><strong>MEMBERSHIP TERM:</strong> Unless otherwise specified, a membership will be automatically renewed each month, on a month-to-month basis. Members are financially responsible for all associated renewal fees until notice of cancellation is received.</li>
      <li><strong>CANCELLATIONS:</strong> Cancellations are not retroactive. Therefore, if a member cancels after their membership month has commenced, the member will not be entitled to a refund for that membership month. Cancellations do not become effective until the starting date of the member&#8217;s next membership month. A membership month begins on the numbered date when a member subscribes or renews their membership (e.g. November 30) and concludes on the day before that numbered date for each successive month after (e.g. December 29, January 29th etc.) unless that numbered date does not exist in a successive month (e.g. February 29th) in which case, the closest preceding numbered date in the successive month will be used (e.g. February 28).A member may only cancel by sending an e-mail to help@PersonalSportRecord.com expressly indicating within the body of the message, the member’s unequivocal request to cancel. The message must clearly indicate exactly which products or services the member wishes to have cancelled. The message must include the member’s first and last name, user name and e-mail address. PersonalSportRecord.com will not accept or recognize requests to cancel that do not comply with the requirements herein. Please note that PersonalSportRecord.com will not accept or open any e-mail communications that include attachments.</li>
      <li><strong>WAIVER, RELEASE AND LIMITATION OF LIABILITY:</strong> You agree that neither PersonalSportRecord.com nor its affiliates, subsidiaries, officers, directors, employees, agents, consultants, information providers or suppliers, shall have any liability to you under any theory of liability or indemnity in connection with your use of PersonalSportRecord.com products or services. You hereby release and forever waive any and all claims you may have against PersonalSportRecord.com for losses or damages you sustain in connection with your use of any PersonalSportRecord.com products or services or the use of any other website maintained by PersonalSportRecord.com. If PersonalSportRecord.com, or any of its officers, directors, employees, agents, consultants, information providers or suppliers is held to be liable, notwithstanding the foregoing waiver and release in the preceding paragraph, the total liability of PersonalSportRecord.com, its officers, directors, employees, agents, consultants, information providers and suppliers, if any, for losses or damages shall not exceed the fees actually received by PersonalSportRecord.com from you for the particular product, information or service provided. All other damages, direct or indirect, special, incidental, consequential or punitive arising from any use of the products, information, services or other parts of PersonalSportRecord.com are hereby excluded and waived even if PersonalSportRecord.com or its officers, directors, employees, agents, consultants, information providers or suppliers have been advised of the possibility of such damages. You agree that any and all data entered into the system is the property of PersonalSportRecord.com, including but not limited to all Exercise Programs, and Recipes.</li>
      <li><strong>NOTICE:</strong> PersonalSportRecord.com may deliver notice to you by means of phone, e-mail, text message, a general notice on this website or other website maintained by PersonalSportRecord.com or by written communication delivered by mail to your address on record. Company 1050513 B.C. Ltd. (DBA &#8216;PSR&#8217;)</li>
      </ol>
      <p>&nbsp;</p>
      <p><strong>Company 1050513 B.C. Ltd. (DBA &#8216;PSR&#8217;)</strong></p>
      <p>NO RETURNS, EXCHANGES OR REFUNDS</p>
      <p>All funds payable in Canadian Dollars</p>
      <p>We accept Visa and Master Card</p>
      <p>&nbsp;</p>
      <button className="button expanded theme" onClick={props.onAccepted}>I accept</button>
      <p>&nbsp;</p>
    </div>
  </div>
)
export default Terms;
