export default { ass: { 'Throwing': 'https://player.vimeo.com/video/82153689',
                        'Two Hand Striking': 'https://player.vimeo.com/video/82153220',
                        'Skipping': 'https://player.vimeo.com/video/82153566',
                        'Starting and Stopping': 'https://player.vimeo.com/video/82153567',
                        'Running': 'https://player.vimeo.com/video/82153565',
                        'Rolling': 'https://player.vimeo.com/video/82153381',
                        'Object Manipulation - Feet': 'https://player.vimeo.com/video/82153562',
                        'Object Manipulation - Hands': 'https://player.vimeo.com/video/82153563',
                        'Kicking': 'https://player.vimeo.com/video/82153378',
                        'Jumping': 'https://player.vimeo.com/video/82153376',
                        'Hopping': 'https://player.vimeo.com/video/82153375',
                        'Galloping': 'https://player.vimeo.com/video/82153374',
                        'Falling': 'https://player.vimeo.com/video/82153230',
                        'Dodging': 'https://player.vimeo.com/video/82153227',
                        'Catching': 'https://player.vimeo.com/video/82153224',
                        'Balance': 'https://player.vimeo.com/video/82153222'
                      },
                  //used for the graphs info popup
                 show: { 'Throwing': 'https://player.vimeo.com/video/78299389',
                         'Two Hand Striking': 'https://player.vimeo.com/video/78299384',
                         'Skipping': 'https://player.vimeo.com/video/78301622',
                         'Starting and Stopping': 'https://player.vimeo.com/video/78299390',
                         'Running': 'https://player.vimeo.com/video/78302818',
                         'Rolling': 'https://player.vimeo.com/video/78304591',
                         'Object Manipulation - Feet': 'https://player.vimeo.com/video/78299382',
                         'Object Manipulation - Hands': 'https://player.vimeo.com/video/78299382',
                         'Kicking': 'https://player.vimeo.com/video/78304592',
                         'Jumping': 'https://player.vimeo.com/video/78304590',
                         'Hopping': 'https://player.vimeo.com/video/78301626',
                         'Galloping': 'https://player.vimeo.com/video/78301627',
                         'Falling': 'https://player.vimeo.com/video/78299387',
                         'Dodging': 'https://player.vimeo.com/video/78301628',
                         'Catching': 'https://player.vimeo.com/video/78302817',
                         'Balance': 'https://player.vimeo.com/video/78301625'//hardcoded as a default in info-popup-technical-physical-video-only
                       } }
